baseurl = "https://jordancoinjackson.com"
languageCode = "en"
title = "Life & Times"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/tanksuzuki\">Hemingway Template built by Asuka Suzuki</a> 2016"
disqusShortname = "www-jordancoinjackson-com"
googleAnalytics = "UA-114624886-1"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/JordanCoin"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/CoinJordan"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://firebasestorage.googleapis.com/v0/b/personal-website-80850.appspot.com/o/Resume11-5-18.pdf?alt=media&token=2e29e8ef-0794-4e83-bb0f-d9da92d95bd3"
# fa_icon = "resume-icon.png"
title = "Resume"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
